name: Azure_push_v3

on:
  workflow_dispatch:
  push:
      branches: 
      - master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      
      - name: Setup .NET
        uses: action/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Restore
        run: dotnet restore ./Urb.Plan.v2.sln

      - name: Build
        run: dotnet build ./Urb.Plan.v2.sln --configuration Release --no-restore  

      - name: Publish
        run: dotnet publish ./Urb.Plan.v2.sln --configuration Release --no-build
        
      
        
          
    
  

    
  
    
