name: Azure_push_v5

on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - name: Setup .NET
        uses: actions/setup-dotnet@v2  
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore Urb.Plan.v2.sln

      - name: Build
        run: dotnet build Urb.Plan.v2.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Urb.Plan.v2.sln --configuration Release --no-build
